name: jbus_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.6
  get_it: ^7.2.0
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_native_splash: ^2.3.6
  intl: ^0.18.1
  meta: ^1.10.0
  google_maps_flutter: ^2.5.0
  http: ^1.1.2
  geolocator: ^10.1.0
  retrofit: any
  dio: 5.0.0
  json_annotation: ^4.8.1
  firebase_database: ^10.3.8
  firebase_auth: ^4.15.3
  firebase_storage: ^11.5.6
  shared_preferences: ^2.2.2
  flutter_polyline_points: ^2.0.0
  

flutter_native_splash:
  android: true
  ios: true
  background_image: "assets/logos/splash.png"

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  build_runner: any
  json_serializable: any
  retrofit_generator: ^8.0.6

flutter_icons:
  image_path: "assets/logos/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: PTSerif
      fonts:
        - asset: assets/fonts/PTSerif-Regular.ttf

  assets:
    - assets/
    - assets/images/
    - assets/images/profile_photos/
    - assets/images/profile_photos/boys_avatars/
    - assets/images/profile_photos/girls_avatars/
    - assets/logos/
    - assets/images/galery.png
    - assets/images/protected.png
    - assets/images/visa.png
    - assets/images/chip.png
    - assets/images/visa_background.png
    - assets/images/visa_text.png
    - assets/images/wifi.png
    - assets/images/map.png
